### ISSUE TITLE
Establish a patrolling process

### ISSUE THREAD

**Issue by cbeams** [bisq-network/wiki#11]
To protect against vandalism, to help enforce consistency with guidelines, etc.

This will need something like a Wiki Editor role to be responsible for it. There could be multiple owners of that role, and between them they patrol all new articles and changes. 

This might not be necessary to do right away, but could also be a big help in starting things off in the right direction.

Ideally should be someone who's familiar with Wikipedia editing standards and techniques.

See https://www.mediawiki.org/wiki/Help:Patrolled_edits

**Comment by m52go** [comment]
Is this needed any more? With registrations locked down, only trusted users can make edits (for the most part). 

We have eyeballs following the recent edit stream already (me and @wiz at least, I believe).

@wiz what do you think? Maybe this issue can be closed for now too.

**Comment by wiz** [comment]
Yeah we tried open user registration but it doesn't work because there are spam bots that sign up many accounts quickly and posting lots of spam content. I think the best way is to simply make an easy process to request a wiki account, and recently I've just been getting requests on Keybase and doing it like that for now which seems to work.
