### ISSUE TITLE
Created - Wiki Style Guide

### ISSUE THREAD

**Issue by kemccall** [bisq-network/wiki#25]
Before
https://bisq.wiki/index.php?title=Wiki_style_guidelines&oldid=279

After
https://bisq.wiki/index.php?title=Wiki_style_guidelines&oldid=732

**Comment by m52go** [comment]
Thanks for fleshing this out. It would seem this issue is an extension of #9?

Anyway I've raised 2 concerns with the style guide in 2 separate issues to keep discussion focused.
[
Non-English language articles](https://github.com/bisq-network/wiki/issues/35)

[Tabs, buttons and UI elements](https://github.com/bisq-network/wiki/issues/34)

**Comment by kemccall** [comment]
> Thanks for fleshing this out. It would seem this issue is an extension of #9?
> > yes. Don't know how to disposition that?
> Anyway I've raised 2 concerns with the style guide in 2 separate issues to keep discussion focused.
> [ Non-English language articles](https://github.com/bisq-network/wiki/issues/35)
> 
> [Tabs, buttons and UI elements](https://github.com/bisq-network/wiki/issues/34)
>> Cool
