### ISSUE TITLE
Specifying wallet derivation path

### ISSUE THREAD

**Issue by m52go** [bisq-network/wiki#36]
Currently the [backing up your wallet](https://bisq.wiki/Backing_up_your_wallet) and [restoring your wallet](https://bisq.wiki/Restoring_your_wallet_from_seed) pages both specify the derivation path.

The former page actually mentions it twice.

@kemccall is this intended? Aside from being repetitive, it seems precarious to have to update the same information manually in 3 places.

If repetition is desired, I had suggested [transclusions](https://www.mediawiki.org/wiki/Transclusion) as a way to avoid manual upkeep.

**Comment by kemccall** [comment]
@m52go I'm for no repetition. It seemed to me that it should only be in the "restoring" article, but not being the subject matter expert on the topic I left it in both. 

It seemed in the one article mentioning it twice might have been a good idea (as it is in the same article) because it's rather important.  I'm not wedded to that idea.
