### ISSUE TITLE
Qubes instructions inconsistent reference to bind-dirs

### ISSUE THREAD

**Issue by unman** [bisq-network/wiki#44]
The Qubes instructions suggest using `bind-dirs`.
This is unnecessary, since the instructions *also* say to use a stand alone qube. `Bind-dirs` is used in template based qubes, to make files/directories persistent, that would otherwise be overwritten on reboot, since they belong to the template.
The references to bind-dirs can be removed from these instructions as they stand.

**Comment by m52go** [comment]
@unman I'm sorry for taking so long to get to this -- I'm one of the more active wiki editors but didn't follow this repository.

If you still remember the context of these issues -- I'm not sure I understand. 

#43 seems to be saying there's a problem with the order of the instructions. I tried to rectify this with https://bisq.wiki/index.php?title=Running_Bisq_on_Qubes&diff=2238&oldid=1748.

But this issue seems to be saying that the items on `bind-dirs` aren't needed at all. Does this mean that [1.2.1](https://bisq.wiki/Running_Bisq_on_Qubes#Create_binding_dirs) and [1.2.2](https://bisq.wiki/Running_Bisq_on_Qubes#Configure_binding_dirs) can be removed entirely?

**Comment by unman** [comment]
On Thu, Apr 29, 2021 at 09:01:12AM -0700, m52go wrote:
> @unman I'm sorry for taking so long to get to this -- I'm one of the more active wiki editors but didn't follow this repository.
> 
> If you still remember the context of these issues -- I'm not sure I understand. 
> 
> #43 seems to be saying there's a problem with the order of the instructions. I tried to rectify this with https://bisq.wiki/index.php?title=Running_Bisq_on_Qubes&diff=2238&oldid=1748.
> 
> But this issue seems to be saying that the items on `bind-dirs` aren't needed at all. Does this mean that [1.2.1](https://bisq.wiki/Running_Bisq_on_Qubes#Create_binding_dirs) and [1.2.2](https://bisq.wiki/Running_Bisq_on_Qubes#Configure_binding_dirs) can be removed entirely?
> 

Hi there - I think that I read as creating a standalone qube - if this
is template based, then accept apologies, and please close.
